/**
 * Realtime API resource — WebSocket voice/chat sessions plus the telephony
 * calls API.
 *
 * Raw audio in both directions (`pcm16` @ 24 kHz by default, or G.711) over
 * binary frames or base64 JSON events, server turn detection (Silero VAD +
 * Smart Turn, `semantic_vad` by default; `turn_detection: null` = manual
 * commit), streamed PCM output, barge-in, first messages and per-turn latency
 * metrics.
 *
 * Works with the browser's native `WebSocket`, Node.js >= 22 (global
 * `WebSocket`), Bun, or any compatible implementation (e.g. the `ws` package)
 * passed via `connect({ webSocket })`.
 */

import { HttpClient } from '../http';
import {
  CreateRealtimeModelRequest,
  RealtimeAudioChunk,
  RealtimeAudioFormat,
  RealtimeCall,
  RealtimeCallCreateRequest,
  RealtimeFirstMessage,
  RealtimeFirstSpeaker,
  RealtimeModel,
  RealtimeResponseCreate,
  RealtimeServerEvent,
  RealtimeServerEventMap,
  RealtimeSessionUpdate,
  RealtimeSessionView,
  RealtimeVariables,
  RuntimeContext,
  UpdateRealtimeModelRequest,
} from '../types';

/** Structural subset shared by browser WebSocket, Node global, and `ws`. */
export interface WebSocketLike {
  readyState: number;
  /** Switched from `blob` to `arraybuffer` when present, so binary audio frames decode synchronously. */
  binaryType?: string;
  send(data: string | ArrayBufferLike | ArrayBufferView): void;
  close(code?: number, reason?: string): void;
  addEventListener(type: 'open', listener: () => void): void;
  addEventListener(type: 'close', listener: (event: { code: number; reason: string }) => void): void;
  addEventListener(type: 'error', listener: (event: unknown) => void): void;
  addEventListener(type: 'message', listener: (event: { data: unknown }) => void): void;
}

/**
 * A WebSocket constructor. Header-capable implementations (`ws`, Node >= 22,
 * Bun) are called as `new WebSocket(url, { headers })`; others as `new WebSocket(url)`.
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type WebSocketConstructorLike = new (url: string, ...args: any[]) => WebSocketLike;

/**
 * How `connect()` sends the API key.
 *
 * - `auto` (default): `Authorization: Bearer` header when the WebSocket
 *   implementation can set upgrade headers (the `ws` package, Node >= 22's
 *   global `WebSocket`, Bun), otherwise `?api_key=` (browsers).
 * - `header` / `query`: force one.
 *
 * The server only accepts `?api_key=` for tokens scoped to the realtime
 * service (a URL leaks more easily than a header); full-scope tokens must use
 * the header.
 */
export type RealtimeAuthMode = 'auto' | 'header' | 'query';

export interface RealtimeConnectOptions {
  /**
   * Realtime model or chat model key. The response generator is a
   * session-start choice — it may alternatively be set via `updateSession`
   * before the first response, but locks once the conversation starts.
   */
  model?: string;
  /** Agent key — responses are generated by this agent instead of a raw model. Locked like `model`. */
  agent?: string;
  /**
   * Initial session config. Sent as ONE `session.update` right after the
   * socket opens, merged with `runtimeContext` / `variables` /
   * `firstSpeaker` / `firstMessage` — so a `first_speaker: 'agent'` greeting
   * already sees all of them.
   */
  session?: RealtimeSessionUpdate;
  /**
   * Downstream auth/data for agent tool calls — sent in the initial
   * `session.update`. Also settable/refreshable later via
   * `updateSession({ runtime_context })`.
   */
  runtimeContext?: RuntimeContext;
  /** `{{name}}` template variables (instructions, first message; forwarded to agents). */
  variables?: RealtimeVariables;
  /** Who speaks first. `agent` starts the first message as soon as the initial `session.update` is applied. */
  firstSpeaker?: RealtimeFirstSpeaker;
  /** What the agent says first (overrides the preset). */
  firstMessage?: RealtimeFirstMessage;
  /** How the API key is sent (default `auto`). */
  auth?: RealtimeAuthMode;
  /**
   * Extra upgrade headers, e.g. `X-Cpr-Hdr-*` runtime-context headers.
   * Header-capable WebSocket implementations only (throws otherwise).
   */
  headers?: Record<string, string>;
  /** Custom WebSocket implementation (defaults to the global `WebSocket`). */
  webSocket?: WebSocketConstructorLike;
  /**
   * Give up when the session is not ready this long after `connect()` was
   * called (default 30000; `0` = wait forever). The clock covers the socket
   * opening and the server creating the session.
   */
  timeoutMs?: number;
}

/** Receives decoded response audio — see {@link RealtimeConnection.onAudio}. */
export type RealtimeAudioListener = (chunk: RealtimeAudioChunk) => void;

/** How a connection ended — see {@link RealtimeConnection.onClose}. */
export interface RealtimeCloseInfo {
  /**
   * WebSocket close code: 1000 normal, 1006 dropped, 1009 too much data, 1011 server error, 1013 the
   * server is busy (at its live-session cap; try again shortly), 4401 unauthorized (key, scope or
   * permission refused), 4402 license required (the tenant has no active ENTERPRISE license).
   */
  code: number;
  reason: string;
  /** The transport error reported just before the close, when the socket reported one. */
  error?: Error;
}

/** Receives the end of a connection — see {@link RealtimeConnection.onClose}. */
export type RealtimeCloseListener = (info: RealtimeCloseInfo) => void;

/** Result of {@link RealtimeConnection.respond}. */
export interface RealtimeRespondResult {
  text: string;
  /**
   * Response audio as base64 (when TTS is configured): every frame of the
   * response, either transport, joined in order (raw `output_audio_format`
   * bytes, no container).
   */
  audio?: string;
  /** Id of the response that answered. */
  responseId?: string;
}

export interface RealtimeUrlOptions {
  model?: string;
  agent?: string;
  /** `first_speaker` query parameter. `connect()` sends this in the initial `session.update` instead. */
  firstSpeaker?: RealtimeFirstSpeaker;
  /** `variables` query parameter (JSON). Prefer `session.update` — URLs end up in logs. */
  variables?: RealtimeVariables;
  /** Put the API key in `?api_key=` (default true). Set false when you send an `Authorization` header. */
  includeApiKey?: boolean;
}

type AnyListener = (event: RealtimeServerEvent) => void;

const OPEN = 1;

/** `connect()` gives up after this long without a ready session. */
const DEFAULT_CONNECT_TIMEOUT_MS = 30_000;

/** Responses whose output format is remembered for attributing binary frames (oldest dropped first). */
const MAX_TRACKED_RESPONSES = 16;

/**
 * Server errors raised by audio input, speech output or other events — never
 * by a `response.create`, so they must not fail a pending `respond()`:
 * `tts_failed` leaves the response running and completing; `forbidden` is a
 * `session.update` refused (like `generator_locked`). (`event_too_large` is
 * not listed: an oversized `response.create { input }` is the one request it
 * can be about, and nothing else will answer it.)
 */
const UNRELATED_ERROR_CODES = new Set([
  'invalid_audio',
  'invalid_audio_format',
  'audio_buffer_full',
  'audio_buffer_empty',
  'transcription_failed',
  'tts_failed',
  'invalid_item',
  'generator_locked',
  'forbidden',
  'unknown_event',
  'invalid_json',
]);

/** Wire audio formats (input and output). */
const AUDIO_FORMATS = new Set<string>(['pcm16', 'g711_ulaw', 'g711_alaw']);

function asAudioFormat(value: unknown): RealtimeAudioFormat | null {
  return typeof value === 'string' && AUDIO_FORMATS.has(value) ? (value as RealtimeAudioFormat) : null;
}

/**
 * A live realtime connection. Listen with `on(type, cb)` (use `'*'` for all
 * events), consume audio with `onAudio(cb)`, stream microphone audio with
 * `sendAudio(bytes)`, or use the high-level `respond()` helper for simple
 * turn-taking.
 */
export class RealtimeConnection {
  private socket: WebSocketLike;
  private listeners = new Map<string, Set<AnyListener>>();
  private audioListeners = new Set<RealtimeAudioListener>();
  /** Latest session echoed by the server (`session.created` / `session.updated`). */
  private serverSession: RealtimeSessionView | null = null;
  /** Audio settings this client asked for — used until the server echoes its own. */
  private requested: { output?: RealtimeAudioFormat; outputRate?: number } = {};
  /** Responses created and not yet done. */
  private openResponses = new Set<string>();
  /** Response the next binary audio frame belongs to (binary frames carry no id). */
  private audioResponseId: string | null = null;
  /**
   * Output format and rate each response started with. The server fixes them
   * when a response starts and binary frames do not say, so a mid-response
   * `session.update` must not relabel the frames still on the wire.
   */
  private responseAudio = new Map<string, { format: RealtimeAudioFormat; sampleRate: number }>();
  /** Sentence announced by `response.audio_transcript.delta`, attached to the next binary frame. */
  private pendingAudioText: string | undefined;
  /** Non-null while a Blob frame is being read; later frames queue behind it to keep their order. */
  private inbox: Promise<void> | null = null;
  private inboxDepth = 0;
  /** Set (briefly) by {@link holdFrames}; frames queue until it settles. */
  private held: Promise<void> | null = null;
  /** Set once the socket closed — by the server, the network or {@link close}. */
  private closeInfo: RealtimeCloseInfo | null = null;
  private closeListeners = new Set<RealtimeCloseListener>();
  /** Calls that can no longer finish once the socket is gone (`respond()`); each rejects its caller. */
  private waiters = new Set<(error: Error) => void>();
  /** Last transport error, reported with the close that follows it. */
  private socketError: Error | undefined;

  constructor(socket: WebSocketLike) {
    this.socket = socket;
    // Browsers and undici deliver binary frames as Blob by default, which can
    // only be read asynchronously — ArrayBuffer keeps audio in event order.
    if (socket.binaryType === 'blob') socket.binaryType = 'arraybuffer';
    socket.addEventListener('message', (event: { data: unknown }) => this.receive(event.data));
    socket.addEventListener('error', (event: unknown) => {
      this.socketError = toSocketError(event, 'WebSocket error');
    });
    socket.addEventListener('close', (event: { code: number; reason: string }) => this.handleClose(event));
  }

  /** Latest session config echoed by the server, or `null` before `session.created`. */
  get session(): RealtimeSessionView | null {
    return this.serverSession;
  }

  /** `null` while the connection is open; how it ended once it closed (see {@link onClose}). */
  get closed(): RealtimeCloseInfo | null {
    return this.closeInfo;
  }

  /**
   * Be told when the connection ends — the server closed it (`4401`
   * unauthorized, `4402` license required, `1013` server busy, `1009` too
   * much data, `1011` server error…), the network
   * dropped, or {@link close} was called. Calls to {@link respond} still
   * pending at that point reject. Returns an unsubscribe function. A listener
   * added after the close is called right away (asynchronously).
   */
  onClose(listener: RealtimeCloseListener): () => void {
    const info = this.closeInfo;
    if (info) {
      let active = true;
      void Promise.resolve().then(() => {
        if (active) listener(info);
      });
      return () => {
        active = false;
      };
    }
    this.closeListeners.add(listener);
    return () => {
      this.closeListeners.delete(listener);
    };
  }

  private handleClose(event: { code: number; reason: string } | undefined): void {
    if (this.closeInfo) return;
    const info: RealtimeCloseInfo = {
      code: typeof event?.code === 'number' ? event.code : 1005,
      reason: typeof event?.reason === 'string' ? event.reason : '',
      ...(this.socketError ? { error: this.socketError } : {}),
    };
    this.closeInfo = info;
    this.failWaiters(new Error(`Realtime socket closed (${describeClose(info)})`));
    const listeners = [...this.closeListeners];
    this.closeListeners.clear();
    for (const listener of listeners) listener(info);
  }

  /** Reject whatever is waiting on this connection (the socket is gone, so nothing will answer). */
  private failWaiters(error: Error): void {
    const waiters = [...this.waiters];
    this.waiters.clear();
    for (const fail of waiters) fail(error);
  }

  /** Subscribe to a server event type, or `'*'` for every event. Returns an unsubscribe function. */
  on<K extends keyof RealtimeServerEventMap>(type: K, listener: (event: RealtimeServerEventMap[K]) => void): () => void;
  on(type: string, listener: (event: RealtimeServerEvent) => void): () => void;
  on(type: string, listener: (event: never) => void): () => void {
    const set = this.listeners.get(type) ?? new Set<AnyListener>();
    const stored = listener as unknown as AnyListener;
    set.add(stored);
    this.listeners.set(type, set);
    return () => set.delete(stored);
  }

  off(type: string, listener: (event: never) => void): void {
    this.listeners.get(type)?.delete(listener as unknown as AnyListener);
  }

  /**
   * Subscribe to response audio from either transport — JSON
   * `response.audio.delta` or binary frames (`audio_transport: 'binary'`).
   * Every chunk carries the raw `bytes` and decoded `pcm` samples (Int16,
   * mono, `sampleRate`; G.711 is decoded too). On
   * `output_audio_buffer.cleared`, flush whatever playback is queued.
   */
  onAudio(listener: RealtimeAudioListener): () => void {
    this.audioListeners.add(listener);
    return () => this.audioListeners.delete(listener);
  }

  private dispatch(event: RealtimeServerEvent): void {
    for (const listener of this.listeners.get(event.type) ?? []) listener(event);
    for (const listener of this.listeners.get('*') ?? []) listener(event);
  }

  private emitAudio(chunk: RealtimeAudioChunk): void {
    for (const listener of this.audioListeners) listener(chunk);
  }

  // ── Inbound frames ──────────────────────────────────────────────────

  private receive(data: unknown): void {
    if (this.inboxDepth === 0 && !this.held && !isBlobLike(data)) {
      this.handleFrame(data);
      return;
    }
    this.inboxDepth++;
    this.inbox = (this.inbox ?? Promise.resolve())
      .then(async () => {
        await this.held;
        this.handleFrame(isBlobLike(data) ? new Uint8Array(await data.arrayBuffer()) : data);
      })
      .catch(() => undefined)
      .then(() => {
        if (--this.inboxDepth === 0) this.inbox = null;
      });
  }

  /**
   * Make the frames that follow wait until the current task is over.
   * `connect()` resolves while `session.created` is being dispatched, and its
   * caller only attaches listeners once the `await` continues — but one socket
   * read can carry more frames than that one: the echo of the initial
   * `session.update`, a text greeting. Dispatched on the spot they would reach
   * nobody; queued, they arrive in order right after the caller has had its turn.
   */
  private holdFrames(): void {
    if (this.held) return;
    const held: Promise<void> = new Promise<void>((resolve) => setTimeout(resolve, 0)).then(() => {
      if (this.held === held) this.held = null;
    });
    this.held = held;
  }

  private handleFrame(data: unknown): void {
    if (typeof data === 'string') {
      this.handleText(data, false);
      return;
    }
    const bytes = frameBytes(data);
    if (!bytes) {
      this.handleText(String(data), false);
      return;
    }
    // Some WebSocket implementations hand text frames over as bytes too.
    if (looksLikeJsonObject(bytes) && this.handleText(utf8Decode(bytes), true)) return;
    this.handleBinaryAudio(bytes);
  }

  /** Parse and dispatch one JSON event. `strict` = only accept a `{ type }` object (bytes that may be audio). */
  private handleText(text: string, strict: boolean): boolean {
    let parsed: RealtimeServerEvent;
    try {
      parsed = JSON.parse(text) as RealtimeServerEvent;
    } catch {
      return false;
    }
    if (!parsed || typeof parsed !== 'object') return false;
    if (strict && typeof parsed.type !== 'string') return false;
    this.track(parsed);
    this.dispatch(parsed);
    if (parsed.type === 'response.audio.delta') this.handleAudioDelta(parsed);
    if (parsed.type === 'session.created') this.holdFrames();
    return true;
  }

  /** Bookkeeping that keeps binary frames attributable and audio formats known. */
  private track(event: RealtimeServerEvent): void {
    switch (event.type) {
      case 'session.created':
      case 'session.updated':
        if (event.session && typeof event.session === 'object') {
          this.serverSession = event.session as RealtimeSessionView;
        }
        break;
      case 'response.created': {
        const id = (event.response as { id?: unknown } | undefined)?.id;
        if (typeof id === 'string') {
          this.openResponses.add(id);
          this.audioResponseId = id;
          this.pendingAudioText = undefined;
          this.rememberOutputAudio(id);
        }
        break;
      }
      case 'response.audio_transcript.delta':
        if (typeof event.response_id === 'string') this.audioResponseId = event.response_id;
        if (typeof event.delta === 'string') this.pendingAudioText = event.delta;
        break;
      case 'output_audio_buffer.cleared':
        this.pendingAudioText = undefined;
        break;
      case 'response.done':
        if (typeof event.response_id === 'string') this.openResponses.delete(event.response_id);
        break;
    }
  }

  private handleAudioDelta(event: RealtimeServerEvent): void {
    if (typeof event.audio !== 'string') return;
    if (typeof event.response_id === 'string') this.audioResponseId = event.response_id;
    // The JSON delta carries its own sentence text; a pending transcript delta is spent.
    this.pendingAudioText = undefined;
    if (this.audioListeners.size === 0) return;
    const fallback = this.outputAudio();
    const format = asAudioFormat(event.format) ?? fallback.format;
    const sampleRate = typeof event.sample_rate === 'number'
      ? event.sample_rate
      : format === fallback.format ? fallback.sampleRate : defaultSampleRate(format);
    const contentType = typeof event.content_type === 'string'
      ? event.content_type
      : contentTypeFor(format, sampleRate);
    const bytes = base64ToBytes(event.audio);
    this.emitAudio({
      responseId: this.audioResponseId,
      format,
      sampleRate,
      contentType,
      bytes,
      pcm: decodePcm(format, bytes),
      text: typeof event.text === 'string' ? event.text : undefined,
      transport: 'json',
    });
  }

  private handleBinaryAudio(bytes: Uint8Array): void {
    const text = this.pendingAudioText;
    this.pendingAudioText = undefined;
    if (this.audioListeners.size === 0) return;
    // The response's own format; the session echo only for frames that cannot be attributed.
    const { format, sampleRate } = (this.audioResponseId && this.responseAudio.get(this.audioResponseId))
      || this.outputAudio();
    this.emitAudio({
      responseId: this.audioResponseId,
      format,
      sampleRate,
      contentType: contentTypeFor(format, sampleRate),
      bytes,
      pcm: decodePcm(format, bytes),
      text,
      transport: 'binary',
    });
  }

  /** Output format/rate of binary frames: the server's echo wins over what this client requested. */
  private outputAudio(): { format: RealtimeAudioFormat; sampleRate: number } {
    const session = this.serverSession;
    const format = asAudioFormat(session?.output_audio_format) ?? this.requested.output ?? 'pcm16';
    if (format !== 'pcm16') return { format, sampleRate: 8000 };
    const rate = typeof session?.output_audio_sample_rate === 'number' && asAudioFormat(session?.output_audio_format)
      ? session.output_audio_sample_rate
      : this.requested.outputRate ?? 24000;
    return { format, sampleRate: rate };
  }

  /** The server fixes a response's output format when it creates the response — note it, like the server does. */
  private rememberOutputAudio(responseId: string): void {
    this.responseAudio.set(responseId, this.outputAudio());
    if (this.responseAudio.size > MAX_TRACKED_RESPONSES) {
      const oldest = this.responseAudio.keys().next().value;
      if (oldest !== undefined) this.responseAudio.delete(oldest);
    }
  }

  // ── Client events ───────────────────────────────────────────────────

  /** Send a raw client event. */
  send(event: Record<string, unknown>): void {
    this.assertOpen();
    this.socket.send(JSON.stringify(event));
  }

  private assertOpen(): void {
    if (this.socket.readyState !== OPEN) {
      throw new Error(
        this.closeInfo ? `Realtime socket is not open (closed: ${describeClose(this.closeInfo)})` : 'Realtime socket is not open',
      );
    }
  }

  /** Update session config (model, instructions, voice, audio formats, turn detection, first message…). */
  updateSession(session: RealtimeSessionUpdate): void {
    this.send({ type: 'session.update', session });
    if (session.output_audio_format !== undefined) this.requested.output = session.output_audio_format;
    if (session.output_audio_sample_rate !== undefined) this.requested.outputRate = session.output_audio_sample_rate;
  }

  /** Set `{{name}}` template variables (`session.update { variables }`). */
  setVariables(variables: RealtimeVariables): void {
    this.updateSession({ variables });
  }

  /** Append a user/system message to the conversation. */
  createItem(content: string, role: 'user' | 'system' | 'assistant' = 'user'): void {
    this.send({ type: 'conversation.item.create', item: { role, content } });
  }

  /**
   * Append an audio chunk (in the session's `input_audio_format`) as a base64
   * JSON `input_audio_buffer.append`. Strings are sent as-is (already base64);
   * bytes are encoded. {@link sendAudio} sends bytes as a binary frame instead
   * (less overhead).
   */
  appendAudio(audio: string | ArrayBuffer | ArrayBufferView): void {
    const base64 = typeof audio === 'string' ? audio : bytesToBase64(audioBytes(audio));
    this.send({ type: 'input_audio_buffer.append', audio: base64 });
  }

  /**
   * Stream input audio: raw bytes in the session's `input_audio_format`
   * (`pcm16` by default) go out as a binary WebSocket frame — no base64, no
   * JSON. Accepts Buffer / Uint8Array / ArrayBuffer / any typed-array view;
   * an `Int16Array` is sent as s16le and a `Float32Array` (Web Audio samples,
   * -1..1) is converted to `pcm16` first. A base64 string goes out through
   * {@link appendAudio}.
   */
  sendAudio(audio: string | ArrayBuffer | ArrayBufferView): void {
    if (typeof audio === 'string') {
      this.appendAudio(audio);
      return;
    }
    const bytes = audioBytes(audio);
    this.assertOpen();
    this.socket.send(bytes);
  }

  clearAudio(): void {
    this.send({ type: 'input_audio_buffer.clear' });
  }

  /** Transcribe the buffered audio and append it as a user turn (manual turn-taking, `turn_detection: null`). */
  commitAudio(): void {
    this.send({ type: 'input_audio_buffer.commit' });
  }

  /**
   * Ask the server to generate (and stream) the next assistant response.
   * `input` appends a user message first; `first_message: true` runs the
   * first-message logic now.
   */
  createResponse(overrides?: RealtimeResponseCreate): void {
    this.send({ type: 'response.create', response: overrides });
  }

  /** Speak the first message now (`response.create { first_message: true }`). */
  startFirstMessage(): void {
    this.createResponse({ first_message: true });
  }

  cancelResponse(): void {
    this.send({ type: 'response.cancel' });
  }

  /**
   * Report playback progress (`output_audio_buffer.played`). On an
   * interruption the server truncates the assistant's history entry to
   * roughly what was heard. Optional; send it every few hundred ms while
   * playing and once when playback is flushed.
   */
  reportPlayback(responseId: string, playedMs: number): void {
    this.send({
      type: 'output_audio_buffer.played',
      response_id: responseId,
      played_ms: Math.max(0, Math.round(playedMs)),
    });
  }

  /**
   * High-level helper: send a user message, wait for the full response.
   * Resolves with the final text (and base64 audio when TTS is configured).
   *
   * Only the response to THIS message counts. The message goes out as one
   * `response.create { input }`, so the server echoes the user item
   * (`conversation.item.created`) and starts answering it in the same step:
   * the first `response.created` after that echo is ours. Anything else — a
   * greeting that started (or is about to start) on connect, a voice turn —
   * is ignored, even when it begins after this call.
   *
   * Rejects when the response fails or is blocked, on a server error that can
   * only come from this request (audio and speech errors do not count: a
   * sentence whose speech failed still completes), when the socket closes or
   * {@link close} is called, and after `timeoutMs` (default 120000).
   */
  respond(content: string, options?: { timeoutMs?: number }): Promise<RealtimeRespondResult> {
    const timeoutMs = options?.timeoutMs ?? 120_000;
    // The server ignores an empty `input`: there would be no echo to wait for.
    if (!content) return Promise.reject(new Error('respond() needs a non-empty message'));
    const earlier = new Set(this.openResponses);
    const wanted = content.trim();
    let echoed = false;
    let ourId: string | null = null;
    const isOurs = (responseId: unknown) => ourId !== null && responseId === ourId;
    return new Promise((resolve, reject) => {
      let text = '';
      const audio: Uint8Array[] = [];
      const offs: Array<() => void> = [];
      const finish = (settle: () => void) => {
        clearTimeout(timer);
        offs.forEach((off) => off());
        settle();
      };
      const fail = (error: Error) => finish(() => reject(error));
      const timer = setTimeout(() => fail(new Error('Realtime response timed out')), timeoutMs);

      offs.push(this.on('conversation.item.created', (event) => {
        if (echoed) return;
        const item = event.item as { role?: unknown; content?: unknown } | undefined;
        if (item?.role !== 'user') return;
        if (typeof item.content === 'string' && item.content.trim() !== wanted) return;
        echoed = true;
      }));
      offs.push(this.on('response.created', (event) => {
        const id = (event.response as { id?: unknown } | undefined)?.id;
        if (typeof id !== 'string' || earlier.has(id)) return;
        if (echoed && ourId === null) ourId = id;
      }));
      offs.push(this.on('response.output_text.done', (event) => {
        if (isOurs(event.response_id)) text = String(event.text ?? '');
      }));
      offs.push(this.onAudio((chunk) => {
        if (isOurs(chunk.responseId)) audio.push(chunk.bytes);
      }));
      offs.push(this.on('response.done', (event) => {
        if (!isOurs(event.response_id)) return;
        if (event.status === 'completed' || event.status === 'cancelled') {
          finish(() => resolve({
            text,
            audio: audio.length > 0 ? bytesToBase64(concatBytes(audio)) : undefined,
            responseId: event.response_id,
          }));
        } else {
          fail(new Error(event.error?.message ?? `Response ${event.status ?? 'failed'}`));
        }
      }));
      offs.push(this.on('error', (event) => {
        if (UNRELATED_ERROR_CODES.has(String(event.error?.code))) return;
        fail(new Error(event.error?.message ?? 'Realtime error'));
      }));
      offs.push(this.watch(fail));

      try {
        this.createResponse({ input: content });
      } catch (error) {
        // Not open (any more): nothing was sent, so nothing to wait for.
        fail(error instanceof Error ? error : new Error(String(error)));
      }
    });
  }

  /** Reject `fail` when the socket goes away before the caller's work is done; returns the way to stop watching. */
  private watch(fail: (error: Error) => void): () => void {
    this.waiters.add(fail);
    return () => {
      this.waiters.delete(fail);
    };
  }

  /** Close the socket. A {@link respond} still pending rejects; {@link onClose} listeners hear the close itself. */
  close(): void {
    this.socket.close();
    this.failWaiters(new Error('Realtime connection closed'));
  }
}

/**
 * Realtime models — named session presets (chat + STT + TTS + voice +
 * instructions bundled under one key). Connect with `?model=<key>`.
 */
export class RealtimeModelsResource {
  private http: HttpClient;

  constructor(http: HttpClient) {
    this.http = http;
  }

  /** List realtime models. */
  async list(): Promise<RealtimeModel[]> {
    const res = await this.http.request<{ data: RealtimeModel[] }>(
      'GET',
      '/api/client/v1/realtime/models',
    );
    return res.data ?? [];
  }

  /** Create a realtime model preset. */
  async create(data: CreateRealtimeModelRequest): Promise<RealtimeModel> {
    return this.http.request<RealtimeModel>('POST', '/api/client/v1/realtime/models', { body: data });
  }

  /** Fetch one realtime model by id. */
  async retrieve(modelId: string): Promise<RealtimeModel> {
    return this.http.request<RealtimeModel>(
      'GET',
      `/api/client/v1/realtime/models/${encodeURIComponent(modelId)}`,
    );
  }

  /** Update a realtime model preset. */
  async update(modelId: string, data: UpdateRealtimeModelRequest): Promise<RealtimeModel> {
    return this.http.request<RealtimeModel>(
      'PATCH',
      `/api/client/v1/realtime/models/${encodeURIComponent(modelId)}`,
      { body: data },
    );
  }

  /** Delete a realtime model preset. */
  async delete(modelId: string): Promise<{ deleted: boolean; id: string }> {
    return this.http.request<{ deleted: boolean; id: string }>(
      'DELETE',
      `/api/client/v1/realtime/models/${encodeURIComponent(modelId)}`,
    );
  }
}

/** Options of {@link RealtimeCallsResource.get}. */
export interface RealtimeCallGetOptions {
  /** Ask Twilio for the live call state before answering (`?refresh=true`). */
  refresh?: boolean;
}

/**
 * Telephony calls — the Console dials out through the preset's Twilio
 * connection and runs the conversation server-side. Follow it with
 * `get(sessionId)` or the session logs; end it with `hangup(sessionId)`.
 */
export class RealtimeCallsResource {
  private http: HttpClient;

  constructor(http: HttpClient) {
    this.http = http;
  }

  /** Place an outbound call. Resolves once Twilio accepted it (status `queued` / `ringing`). */
  async create(data: RealtimeCallCreateRequest): Promise<RealtimeCall> {
    return this.http.request<RealtimeCall>('POST', '/api/client/v1/realtime/calls', { body: data });
  }

  /**
   * Current call state (status, Twilio SID, answered-by, duration). The state
   * is kept up to date by Twilio's status callbacks; if one was lost (a call
   * shows `ringing` or `in-progress` long after it ended), `{ refresh: true }`
   * asks Twilio for the live state first.
   */
  async get(sessionId: string, options?: RealtimeCallGetOptions): Promise<RealtimeCall> {
    const path = `/api/client/v1/realtime/calls/${encodeURIComponent(sessionId)}`;
    return options?.refresh
      ? this.http.request<RealtimeCall>('GET', path, { query: { refresh: true } })
      : this.http.request<RealtimeCall>('GET', path);
  }

  /** Hang up a ringing or in-progress call. */
  async hangup(sessionId: string): Promise<RealtimeCall> {
    return this.http.request<RealtimeCall>(
      'POST',
      `/api/client/v1/realtime/calls/${encodeURIComponent(sessionId)}/hangup`,
    );
  }
}

export class RealtimeResource {
  private baseURL: string;
  private apiKey: string;

  /** Realtime model presets (CRUD). */
  public models: RealtimeModelsResource;

  /** Telephony calls (outbound dial, status, hang up). */
  public calls: RealtimeCallsResource;

  constructor(baseURL: string, apiKey: string, http: HttpClient) {
    this.baseURL = baseURL;
    this.apiKey = apiKey;
    this.models = new RealtimeModelsResource(http);
    this.calls = new RealtimeCallsResource(http);
  }

  /** Build the websocket URL (useful for custom clients). */
  url(options?: RealtimeUrlOptions): string {
    const params = new URLSearchParams();
    if (options?.includeApiKey !== false) params.set('api_key', this.apiKey);
    if (options?.model) params.set('model', options.model);
    if (options?.agent) params.set('agent', options.agent);
    if (options?.firstSpeaker) params.set('first_speaker', options.firstSpeaker);
    if (options?.variables) params.set('variables', JSON.stringify(options.variables));
    const query = params.toString();
    return `${this.wsBase()}/api/client/v1/realtime${query ? `?${query}` : ''}`;
  }

  private wsBase(): string {
    return this.baseURL.replace(/^http/i, 'ws');
  }

  /**
   * Open a realtime session. Resolves once the server has created the session
   * (`session.created`), not when the socket opens: the server accepts the
   * upgrade first and checks the key, the preset and the agent afterwards. A
   * refused session — invalid or unscoped key, disabled preset, unknown agent
   * — rejects with the server's reason, as does a connection that fails or is
   * not ready within `timeoutMs`.
   */
  async connect(options?: RealtimeConnectOptions): Promise<RealtimeConnection> {
    const globalCtor = (globalThis as { WebSocket?: WebSocketConstructorLike }).WebSocket;
    const Ctor = options?.webSocket ?? globalCtor;
    if (!Ctor) {
      throw new Error(
        'No WebSocket implementation found. Pass one via connect({ webSocket }), e.g. `import WebSocket from "ws"`.',
      );
    }
    const mode = options?.auth ?? 'auto';
    const viaHeader = mode === 'header' || (mode === 'auto' && canSetUpgradeHeaders(Ctor, globalCtor));
    if (options?.headers && !viaHeader) {
      throw new Error(
        'connect({ headers }) needs a WebSocket implementation that can set upgrade headers (e.g. the `ws` package).',
      );
    }
    const url = this.url({ model: options?.model, agent: options?.agent, includeApiKey: !viaHeader });
    const socket = viaHeader
      ? new Ctor(url, { headers: { ...options?.headers, Authorization: `Bearer ${this.apiKey}` } })
      : new Ctor(url);
    // Listen before the socket opens so `session.created` is never missed.
    const connection = new RealtimeConnection(socket);
    await awaitSession(socket, connection, options);
    return connection;
  }
}

/**
 * Wait for the server to accept the session. The initial `session.update`
 * goes out as soon as the socket opens: the server holds early messages while
 * it authenticates and replays them in order, so a greeting still starts from
 * it. Anything that ends the connection before `session.created` — an `error`
 * event (always followed by a close), a close, a transport error, the timeout —
 * rejects, and the socket is closed.
 */
function awaitSession(
  socket: WebSocketLike,
  connection: RealtimeConnection,
  options: RealtimeConnectOptions | undefined,
): Promise<void> {
  const timeoutMs = options?.timeoutMs ?? DEFAULT_CONNECT_TIMEOUT_MS;
  return new Promise<void>((resolve, reject) => {
    const offs: Array<() => void> = [];
    let timer: ReturnType<typeof setTimeout> | undefined;
    let opened = false;
    let settled = false;
    const settle = (error?: Error) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      offs.forEach((off) => off());
      if (!error) {
        resolve();
        return;
      }
      connection.close();
      reject(error);
    };

    if (Number.isFinite(timeoutMs) && timeoutMs > 0) {
      timer = setTimeout(() => {
        settle(new Error(
          `Realtime session not ready after ${timeoutMs} ms (${opened ? 'the socket is open, the server has not created the session' : 'the socket did not open'})`,
        ));
      }, timeoutMs);
    }
    socket.addEventListener('open', () => {
      opened = true;
      try {
        const initial = initialSessionUpdate(options);
        if (initial) connection.updateSession(initial);
      } catch (error) {
        settle(error instanceof Error ? error : new Error(String(error)));
      }
    });
    socket.addEventListener('error', (event: unknown) => settle(toSocketError(event, 'WebSocket connection failed')));
    offs.push(connection.onClose((info) => settle(new Error(
      opened
        ? `WebSocket closed before the session was created (${describeClose(info)})`
        : `WebSocket closed before opening (code ${info.code})`,
    ))));
    offs.push(connection.on('error', (event) => {
      const { message, code } = event.error ?? {};
      settle(new Error(`Realtime connection refused: ${message ?? 'unknown error'}${code ? ` (${code})` : ''}`));
    }));
    offs.push(connection.on('session.created', () => settle()));
  });
}

/** Merge the connect-time session options into one `session.update` (or none). */
function initialSessionUpdate(options?: RealtimeConnectOptions): RealtimeSessionUpdate | null {
  if (!options) return null;
  const session: RealtimeSessionUpdate = { ...options.session };
  if (options.runtimeContext) session.runtime_context = options.runtimeContext;
  if (options.variables) session.variables = { ...session.variables, ...options.variables };
  if (options.firstSpeaker) session.first_speaker = options.firstSpeaker;
  if (options.firstMessage) session.first_message = options.firstMessage;
  return Object.keys(session).length > 0 ? session : null;
}

/** Error behind a socket `error` event: an Error as is, the one a `ws` ErrorEvent wraps, else `fallback`. */
function toSocketError(event: unknown, fallback: string): Error {
  if (event instanceof Error) return event;
  const detail = event as { error?: unknown; message?: unknown } | null | undefined;
  if (detail?.error instanceof Error) return detail.error;
  return new Error(typeof detail?.message === 'string' && detail.message ? detail.message : fallback);
}

/** `code 4401: Unauthorized` — a close code with its reason and the transport error that came with it. */
function describeClose(info: RealtimeCloseInfo): string {
  return `code ${info.code}${info.reason ? `: ${info.reason}` : ''}${info.error ? `; ${info.error.message}` : ''}`;
}

/**
 * Whether `new Ctor(url, { headers })` sends the headers: the `ws` package,
 * Bun's and Node >= 22's global `WebSocket` (undici's init dictionary).
 * Browsers cannot set upgrade headers.
 *
 * `ws` is recognised by its shape, in either module system. Only the
 * CommonJS entry (`ws/index.js`) attaches the `Receiver` / `Sender` statics;
 * an ES-module import resolves to `ws/wrapper.mjs`, whose default export is the
 * bare class without them. What every `ws` socket has — and browser and undici
 * sockets lack — is `terminate()`.
 */
function canSetUpgradeHeaders(
  Ctor: WebSocketConstructorLike,
  globalCtor: WebSocketConstructorLike | undefined,
): boolean {
  const statics = Ctor as unknown as Record<string, unknown>;
  if (typeof statics.Receiver === 'function' && typeof statics.Sender === 'function') return true;
  if (typeof (Ctor.prototype as { terminate?: unknown } | undefined)?.terminate === 'function') return true;
  if (Ctor !== globalCtor) return false;
  const versions = (globalThis as { process?: { versions?: Record<string, string | undefined> } }).process?.versions;
  if (!versions || versions.deno) return false;
  if (versions.bun) return true;
  const major = Number(versions.node?.split('.')[0]);
  return Number.isFinite(major) && major >= 22;
}

// ── Audio helpers ─────────────────────────────────────────────────────

const LITTLE_ENDIAN = new Uint8Array(new Uint16Array([1]).buffer)[0] === 1;

/**
 * Convert Web Audio samples (Float32, -1..1) to 16-bit PCM — what
 * `sendAudio()` does with a `Float32Array`.
 */
export function float32ToPcm16(samples: Float32Array): Int16Array {
  const out = new Int16Array(samples.length);
  for (let i = 0; i < samples.length; i++) {
    const s = Math.max(-1, Math.min(1, samples[i]));
    out[i] = s < 0 ? Math.round(s * 0x8000) : Math.round(s * 0x7fff);
  }
  return out;
}

/** Convert 16-bit PCM (e.g. `chunk.pcm` from `onAudio`) to Float32 samples for Web Audio playback. */
export function pcm16ToFloat32(pcm: Int16Array): Float32Array {
  const out = new Float32Array(pcm.length);
  for (let i = 0; i < pcm.length; i++) out[i] = pcm[i] / (pcm[i] < 0 ? 0x8000 : 0x7fff);
  return out;
}

/** Raw bytes for any accepted audio input; Int16 as s16le, Float32 converted to pcm16. */
function audioBytes(audio: ArrayBuffer | ArrayBufferView): Uint8Array {
  if (!ArrayBuffer.isView(audio)) return new Uint8Array(audio);
  if (audio instanceof Float32Array) return int16Bytes(float32ToPcm16(audio));
  if (audio instanceof Int16Array) return int16Bytes(audio);
  if (audio instanceof Uint8Array) return audio;
  return new Uint8Array(audio.buffer, audio.byteOffset, audio.byteLength);
}

function int16Bytes(pcm: Int16Array): Uint8Array {
  if (LITTLE_ENDIAN) return new Uint8Array(pcm.buffer, pcm.byteOffset, pcm.byteLength);
  const out = new Uint8Array(pcm.length * 2);
  const view = new DataView(out.buffer);
  for (let i = 0; i < pcm.length; i++) view.setInt16(i * 2, pcm[i], true);
  return out;
}

/** s16le bytes → samples (an odd trailing byte is dropped). */
function pcm16FromBytes(bytes: Uint8Array): Int16Array {
  const count = bytes.byteLength >> 1;
  if (LITTLE_ENDIAN && bytes.byteOffset % 2 === 0) {
    // Copy so the samples never alias a pooled Buffer.
    return new Int16Array(bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + count * 2));
  }
  const out = new Int16Array(count);
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  for (let i = 0; i < count; i++) out[i] = view.getInt16(i * 2, true);
  return out;
}

let ulawTable: Int16Array | null = null;
let alawTable: Int16Array | null = null;

/** ITU-T G.711 μ-law byte → linear sample. */
function ulawToLinear(value: number): number {
  const u = ~value & 0xff;
  const magnitude = ((((u & 0x0f) << 3) + 0x84) << ((u >> 4) & 0x07)) - 0x84;
  return u & 0x80 ? -magnitude : magnitude;
}

/** ITU-T G.711 A-law byte → linear sample. */
function alawToLinear(value: number): number {
  const a = value ^ 0x55;
  const exponent = (a >> 4) & 0x07;
  const mantissa = a & 0x0f;
  const magnitude = exponent === 0 ? (mantissa << 4) + 8 : ((mantissa << 4) + 0x108) << (exponent - 1);
  return a & 0x80 ? magnitude : -magnitude;
}

function g711Decode(bytes: Uint8Array, law: 'ulaw' | 'alaw'): Int16Array {
  let table = law === 'ulaw' ? ulawTable : alawTable;
  if (!table) {
    table = new Int16Array(256);
    for (let i = 0; i < 256; i++) table[i] = law === 'ulaw' ? ulawToLinear(i) : alawToLinear(i);
    if (law === 'ulaw') ulawTable = table;
    else alawTable = table;
  }
  const out = new Int16Array(bytes.length);
  for (let i = 0; i < bytes.length; i++) out[i] = table[bytes[i]];
  return out;
}

function decodePcm(format: RealtimeAudioFormat, bytes: Uint8Array): Int16Array {
  if (format === 'g711_ulaw') return g711Decode(bytes, 'ulaw');
  if (format === 'g711_alaw') return g711Decode(bytes, 'alaw');
  return pcm16FromBytes(bytes);
}

function defaultSampleRate(format: RealtimeAudioFormat): number {
  return format === 'pcm16' ? 24000 : 8000;
}

/** MIME type of a frame — the same strings the server sends as `content_type`. */
function contentTypeFor(format: RealtimeAudioFormat, sampleRate: number): string {
  if (format === 'g711_ulaw') return 'audio/PCMU;rate=8000';
  if (format === 'g711_alaw') return 'audio/PCMA;rate=8000';
  return `audio/L16;rate=${sampleRate}`;
}

// ── Frame/byte helpers ───────────────────────────────────────────────

interface BlobLike {
  arrayBuffer(): Promise<ArrayBuffer>;
}

function isBlobLike(data: unknown): data is BlobLike {
  return typeof data === 'object' && data !== null && !ArrayBuffer.isView(data)
    && typeof (data as { arrayBuffer?: unknown }).arrayBuffer === 'function';
}

/** Binary frame payload as bytes: ArrayBuffer, any view (Node Buffer), or `ws` fragments. */
function frameBytes(data: unknown): Uint8Array | null {
  if (data instanceof Uint8Array) return data;
  if (ArrayBuffer.isView(data)) return new Uint8Array(data.buffer, data.byteOffset, data.byteLength);
  if (data instanceof ArrayBuffer) return new Uint8Array(data);
  if (Array.isArray(data) && data.length > 0 && data.every((part) => part instanceof Uint8Array)) {
    return concatBytes(data as Uint8Array[]);
  }
  return null;
}

/** `{ … }` — cheap pre-check before trying to read bytes as a JSON event. */
function looksLikeJsonObject(bytes: Uint8Array): boolean {
  return bytes.length >= 2 && bytes[0] === 0x7b && bytes[bytes.length - 1] === 0x7d;
}

function utf8Decode(bytes: Uint8Array): string {
  const globals = globalThis as {
    TextDecoder?: new () => { decode(input: Uint8Array): string };
    Buffer?: { from(data: Uint8Array): { toString(encoding: string): string } };
  };
  if (globals.TextDecoder) return new globals.TextDecoder().decode(bytes);
  if (globals.Buffer) return globals.Buffer.from(bytes).toString('utf8');
  return String.fromCharCode(...bytes);
}

function concatBytes(parts: Uint8Array[]): Uint8Array {
  const out = new Uint8Array(parts.reduce((sum, part) => sum + part.byteLength, 0));
  let offset = 0;
  for (const part of parts) {
    out.set(part, offset);
    offset += part.byteLength;
  }
  return out;
}

function bytesToBase64(bytes: Uint8Array): string {
  const globals = globalThis as {
    Buffer?: { from(data: Uint8Array): { toString(encoding: string): string } };
    btoa?: (data: string) => string;
  };
  if (globals.Buffer) {
    return globals.Buffer.from(bytes).toString('base64');
  }
  let binary = '';
  for (let i = 0; i < bytes.length; i++) binary += String.fromCharCode(bytes[i]);
  if (!globals.btoa) throw new Error('No base64 encoder available');
  return globals.btoa(binary);
}

function base64ToBytes(base64: string): Uint8Array {
  const globals = globalThis as {
    Buffer?: { from(data: string, encoding: string): Uint8Array };
    atob?: (data: string) => string;
  };
  if (globals.Buffer) {
    const buf = globals.Buffer.from(base64, 'base64');
    return new Uint8Array(buf.buffer, buf.byteOffset, buf.byteLength);
  }
  if (!globals.atob) throw new Error('No base64 decoder available');
  const binary = globals.atob(base64);
  const out = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) out[i] = binary.charCodeAt(i);
  return out;
}
